name: Build and Deploy to build-dev

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Use the version your project requires

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Run the build script
      - name: Build project
        run: npm run build

      # Step 5: Deploy to the build-dev branch
      - name: Deploy to build-dev
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -B build-dev
          git add dist -f
          git commit -m "Deploy build to build-dev branch"
          git push -u origin build-dev --force
