name: Build and Deploy to build-dev

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Step 3: Install dependencies and build
      - name: Install and Build
        run: |
          npm ci
          npm run build

      # Step 4: Deploy dist to build-dev
      - name: Deploy dist to build-dev
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch origin build-dev || git branch build-dev
          git checkout -B build-dev origin/build-dev || git checkout -b build-dev
          git rm -rf . # Remove existing files
          cp -r dist/* . # Copy new build files
          git add .
          git commit -m "Deploy new build from develop branch"
          git push --force origin build-dev
