name: Build and Deploy to build-main

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Update if your project requires a different version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Run the build script
      - name: Build project
        run: npm run build

      # Step 5: Deploy to build-main branch
      - name: Deploy to build-main
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -B build-main
          git add dist -f
          git commit -m "Deploy build to build-main branch"
          git push -u origin build-main --force
