name: kyo-web-online - Build and Deploy to build-main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Install ImageMagick
        run: sudo apt-get update && sudo apt-get install -y imagemagick

      - name: Build App
        run: npm run build-all

      - name: Push to build-main
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build-main
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build in Main Environment: ({sha}) {msg}"
