name: kyo-web-online - Build and Deploy to build-dev

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Install Node.js and npm
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20 # Use the version of Node.js your project requires

      # Install ImageMagick
      - name: Setup ImageMagick
        uses: mfinelli/setup-imagemagick@v5.0.1

      # Check Imagemagick
      - name: Check Imagemagick
        run: magick --help

      # Install all dependencies
      - name: Install Dependencies
        run: npm install

      # Install all Runners
      - name: Install Grunt & Webpack
        run: npm install -g grunt-cli webpack-cli

      # Build the project
      - name: Build App
        run: npm run build-all

      # Push the built folder to build-dev branch
      - name: Push to build-dev
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build-dev
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build in Dev Environment: ({sha}) {msg}"
