name: kyo-web-online - Build and Deploy to build-dev

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Setup ImageMagick
        uses: mfinelli/setup-imagemagick@v5.0.1

      - name: Setup Dependencies
        run: sudo apt-get install -y libpng-dev libjpeg-dev libtiff-dev

      - name: Check Imagemagick
        run: source ~/.bashrc && magick --help

      - name: Install Dependencies
        run: npm install

      - name: Install Grunt & Webpack
        run: npm install -g grunt-cli webpack-cli

      - name: Check Favicon Source
        run: ls -la ./src/assets

      - name: Build App
        run: npm run generate-favicons

      - name: Check Favicons
        run: ls -la ./dist/favicons

      - name: Push to build-dev
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build-dev
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build in Dev Environment: ({sha}) {msg}"
