name: kyo-web-online pipeline - go-htmx

on:
  push:
    branches:
      - develop

jobs:
  linter:
    name: golangcli-lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: [stable, oldstable]
        os: [ubuntu-latest]
    env:
      CGO_ENABLED: 0
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Check and Get Dependencies
        run: |

      - name: Install Plugins (plugin-linter)
        run: |
          git clone https://github.com/golangci/example-plugin-linter.git
          cd example-plugin-linter
          go build -o '${{ github.workspace }}/.plugins/example.so' -buildmode=plugin plugin/example.go
        working-directory: ${{ runner.temp }}
        env:
          CGO_ENABLED: 1

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59.1
          install-mode: goinstall
          args: --timeout=10m

      - name: Running All Tests
        run: go test -v -cover ./...

      - name: Build App
        run: go build -v -ldflags "-s -w" -trimpath

      - name: Adding new Changes in build-dev
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build-dev
          FOLDER: build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build in Dev Environment: ({sha}) {msg}"
